import { Bech32Address } from '@keplr-wallet/cosmos';
import { ChainInfoWithExplorer } from './stores/chain';

export const EmbedChainInfos: ChainInfoWithExplorer[] = [
    {
        rpc: 'https://rpc-osmosis.keplr.app',
        rest: 'https://lcd-osmosis.keplr.app',
        chainId: 'osmosis-1',
        chainName: 'Osmosis',
        stakeCurrency: {
            coinDenom: 'OSMO',
            coinMinimalDenom: 'uosmo',
            coinDecimals: 6,
            coinGeckoId: 'osmosis',
            coinImageUrl: window.location.origin + '/public/assets/tokens/osmosis.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('osmo'),
        currencies: [
            {
                coinDenom: 'OSMO',
                coinMinimalDenom: 'uosmo',
                coinDecimals: 6,
                coinGeckoId: 'osmosis',
                coinImageUrl: window.location.origin + '/public/assets/tokens/osmosis.svg',
            },
            {
                coinDenom: 'ION',
                coinMinimalDenom: 'uion',
                coinDecimals: 6,
                coinGeckoId: 'ion',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ion.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'OSMO',
                coinMinimalDenom: 'uosmo',
                coinDecimals: 6,
                coinGeckoId: 'osmosis',
                coinImageUrl: window.location.origin + '/public/assets/tokens/osmosis.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/osmosis/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-cosmoshub.keplr.app',
        rest: 'https://lcd-cosmoshub.keplr.app',
        chainId: 'cosmoshub-4',
        chainName: 'Cosmos Hub',
        stakeCurrency: {
            coinDenom: 'ATOM',
            coinMinimalDenom: 'uatom',
            coinDecimals: 6,
            coinGeckoId: 'cosmos',
            coinImageUrl: window.location.origin + '/public/assets/tokens/cosmos.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('cosmos'),
        currencies: [
            {
                coinDenom: 'ATOM',
                coinMinimalDenom: 'uatom',
                coinDecimals: 6,
                coinGeckoId: 'cosmos',
                coinImageUrl: window.location.origin + '/public/assets/tokens/cosmos.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'ATOM',
                coinMinimalDenom: 'uatom',
                coinDecimals: 6,
                coinGeckoId: 'cosmos',
                coinImageUrl: window.location.origin + '/public/assets/tokens/cosmos.svg',
            },
        ],
        coinType: 118,
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/cosmos/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-columbus.keplr.app',
        rest: 'https://lcd-columbus.keplr.app',
        chainId: 'columbus-5',
        chainName: 'Terra',
        stakeCurrency: {
            coinDenom: 'LUNA',
            coinMinimalDenom: 'uluna',
            coinDecimals: 6,
            coinGeckoId: 'terra-luna',
            coinImageUrl: window.location.origin + '/public/assets/tokens/luna.png',
        },
        bip44: {
            coinType: 330,
        },
        bech32Config: Bech32Address.defaultBech32Config('terra'),
        currencies: [
            {
                coinDenom: 'LUNA',
                coinMinimalDenom: 'uluna',
                coinDecimals: 6,
                coinGeckoId: 'terra-luna',
                coinImageUrl: window.location.origin + '/public/assets/tokens/luna.png',
            },
            {
                coinDenom: 'UST',
                coinMinimalDenom: 'uusd',
                coinDecimals: 6,
                coinGeckoId: 'terrausd',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ust.png',
            },
            {
                coinDenom: 'KRT',
                coinMinimalDenom: 'ukrw',
                coinDecimals: 6,
                coinGeckoId: 'terra-krw',
                coinImageUrl: window.location.origin + '/public/assets/tokens/krt.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'LUNA',
                coinMinimalDenom: 'uluna',
                coinDecimals: 6,
                coinGeckoId: 'terra-luna',
                coinImageUrl: window.location.origin + '/public/assets/tokens/luna.png',
            },
            {
                coinDenom: 'UST',
                coinMinimalDenom: 'uusd',
                coinDecimals: 6,
                coinGeckoId: 'terrausd',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ust.png',
            },
        ],
        gasPriceStep: {
            low: 0.015,
            average: 0.015,
            high: 0.015,
        },
        features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
        explorerUrlToTx: 'https://finder.terra.money/columbus-5/tx/{txHash}',
    },
    {
        rpc: 'https://rpc-secret.keplr.app',
        rest: 'https://lcd-secret.keplr.app',
        chainId: 'secret-4',
        chainName: 'Secret Network',
        stakeCurrency: {
            coinDenom: 'SCRT',
            coinMinimalDenom: 'uscrt',
            coinDecimals: 6,
            coinGeckoId: 'secret',
            coinImageUrl: window.location.origin + '/public/assets/tokens/scrt.svg',
        },
        bip44: {
            coinType: 529,
        },
        bech32Config: Bech32Address.defaultBech32Config('secret'),
        currencies: [
            {
                coinDenom: 'SCRT',
                coinMinimalDenom: 'uscrt',
                coinDecimals: 6,
                coinGeckoId: 'secret',
                coinImageUrl: window.location.origin + '/public/assets/tokens/scrt.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'SCRT',
                coinMinimalDenom: 'uscrt',
                coinDecimals: 6,
                coinGeckoId: 'secret',
                coinImageUrl: window.location.origin + '/public/assets/tokens/scrt.svg',
            },
        ],
        coinType: 118,
        features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
        explorerUrlToTx: 'https://secretnodes.com/secret/chains/secret-4/transactions/{txHash}',
    },
    {
        rpc: 'https://rpc-akash.keplr.app',
        rest: 'https://lcd-akash.keplr.app',
        chainId: 'akashnet-2',
        chainName: 'Akash',
        stakeCurrency: {
            coinDenom: 'AKT',
            coinMinimalDenom: 'uakt',
            coinDecimals: 6,
            coinGeckoId: 'akash-network',
            coinImageUrl: window.location.origin + '/public/assets/tokens/akt.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('akash'),
        currencies: [
            {
                coinDenom: 'AKT',
                coinMinimalDenom: 'uakt',
                coinDecimals: 6,
                coinGeckoId: 'akash-network',
                coinImageUrl: window.location.origin + '/public/assets/tokens/akt.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'AKT',
                coinMinimalDenom: 'uakt',
                coinDecimals: 6,
                coinGeckoId: 'akash-network',
                coinImageUrl: window.location.origin + '/public/assets/tokens/akt.svg',
            },
        ],
        coinType: 118,
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/akash/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-regen.keplr.app',
        rest: 'https://lcd-regen.keplr.app',
        chainId: 'regen-1',
        chainName: 'Regen Network',
        stakeCurrency: {
            coinDenom: 'REGEN',
            coinMinimalDenom: 'uregen',
            coinDecimals: 6,
            coinImageUrl: window.location.origin + '/public/assets/tokens/regen.png',
            coinGeckoId: 'regen',
        },
        bip44: { coinType: 118 },
        bech32Config: Bech32Address.defaultBech32Config('regen'),
        currencies: [
            {
                coinDenom: 'REGEN',
                coinMinimalDenom: 'uregen',
                coinDecimals: 6,
                coinImageUrl: window.location.origin + '/public/assets/tokens/regen.png',
                coinGeckoId: 'regen',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'REGEN',
                coinMinimalDenom: 'uregen',
                coinDecimals: 6,
                coinImageUrl: window.location.origin + '/public/assets/tokens/regen.png',
                coinGeckoId: 'regen',
            },
        ],
        features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
        explorerUrlToTx: 'https://regen.aneka.io/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-sentinel.keplr.app',
        rest: 'https://lcd-sentinel.keplr.app',
        chainId: 'sentinelhub-2',
        chainName: 'Sentinel',
        stakeCurrency: {
            coinDenom: 'DVPN',
            coinMinimalDenom: 'udvpn',
            coinDecimals: 6,
            coinGeckoId: 'sentinel',
            coinImageUrl: window.location.origin + '/public/assets/tokens/dvpn.png',
        },
        bip44: { coinType: 118 },
        bech32Config: Bech32Address.defaultBech32Config('sent'),
        currencies: [
            {
                coinDenom: 'DVPN',
                coinMinimalDenom: 'udvpn',
                coinDecimals: 6,
                coinGeckoId: 'sentinel',
                coinImageUrl: window.location.origin + '/public/assets/tokens/dvpn.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'DVPN',
                coinMinimalDenom: 'udvpn',
                coinDecimals: 6,
                coinGeckoId: 'sentinel',
                coinImageUrl: window.location.origin + '/public/assets/tokens/dvpn.png',
            },
        ],
        explorerUrlToTx: 'https://www.mintscan.io/sentinel/txs/{txHash}',
        features: ['stargate', 'ibc-transfer'],
    },
    {
        rpc: 'https://rpc-persistence.keplr.app',
        rest: 'https://lcd-persistence.keplr.app',
        chainId: 'core-1',
        chainName: 'Persistence',
        stakeCurrency: {
            coinDenom: 'XPRT',
            coinMinimalDenom: 'uxprt',
            coinDecimals: 6,
            coinGeckoId: 'persistence',
            coinImageUrl: window.location.origin + '/public/assets/tokens/xprt.png',
        },
        bip44: {
            coinType: 750,
        },
        bech32Config: Bech32Address.defaultBech32Config('persistence'),
        currencies: [
            {
                coinDenom: 'XPRT',
                coinMinimalDenom: 'uxprt',
                coinDecimals: 6,
                coinGeckoId: 'persistence',
                coinImageUrl: window.location.origin + '/public/assets/tokens/xprt.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'XPRT',
                coinMinimalDenom: 'uxprt',
                coinDecimals: 6,
                coinGeckoId: 'persistence',
                coinImageUrl: window.location.origin + '/public/assets/tokens/xprt.png',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/persistence/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-iris.keplr.app',
        rest: 'https://lcd-iris.keplr.app',
        chainId: 'irishub-1',
        chainName: 'IRISnet',
        stakeCurrency: {
            coinDenom: 'IRIS',
            coinMinimalDenom: 'uiris',
            coinDecimals: 6,
            coinGeckoId: 'iris-network',
            coinImageUrl: window.location.origin + '/public/assets/tokens/iris.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('iaa'),
        currencies: [
            {
                coinDenom: 'IRIS',
                coinMinimalDenom: 'uiris',
                coinDecimals: 6,
                coinGeckoId: 'iris-network',
                coinImageUrl: window.location.origin + '/public/assets/tokens/iris.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'IRIS',
                coinMinimalDenom: 'uiris',
                coinDecimals: 6,
                coinGeckoId: 'iris-network',
                coinImageUrl: window.location.origin + '/public/assets/tokens/iris.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
        explorerUrlToTx: 'https://www.mintscan.io/iris/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-crypto-org.keplr.app/',
        rest: 'https://lcd-crypto-org.keplr.app/',
        chainId: 'crypto-org-chain-mainnet-1',
        chainName: 'Crypto.org',
        stakeCurrency: {
            coinDenom: 'CRO',
            coinMinimalDenom: 'basecro',
            coinDecimals: 8,
            coinGeckoId: 'crypto-com-chain',
            coinImageUrl: window.location.origin + '/public/assets/tokens/cro.png',
        },
        bip44: {
            coinType: 394,
        },
        bech32Config: Bech32Address.defaultBech32Config('cro'),
        currencies: [
            {
                coinDenom: 'CRO',
                coinMinimalDenom: 'basecro',
                coinDecimals: 8,
                coinGeckoId: 'crypto-com-chain',
                coinImageUrl: window.location.origin + '/public/assets/tokens/cro.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'CRO',
                coinMinimalDenom: 'basecro',
                coinDecimals: 8,
                coinGeckoId: 'crypto-com-chain',
                coinImageUrl: window.location.origin + '/public/assets/tokens/cro.png',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/crypto-org/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-iov.keplr.app',
        rest: 'https://lcd-iov.keplr.app',
        chainId: 'iov-mainnet-ibc',
        chainName: 'Starname',
        stakeCurrency: {
            coinDenom: 'IOV',
            coinMinimalDenom: 'uiov',
            coinDecimals: 6,
            coinGeckoId: 'starname',
            coinImageUrl: window.location.origin + '/public/assets/tokens/iov.png',
        },
        bip44: {
            coinType: 234,
        },
        bech32Config: Bech32Address.defaultBech32Config('star'),
        currencies: [
            {
                coinDenom: 'IOV',
                coinMinimalDenom: 'uiov',
                coinDecimals: 6,
                coinGeckoId: 'starname',
                coinImageUrl: window.location.origin + '/public/assets/tokens/iov.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'IOV',
                coinMinimalDenom: 'uiov',
                coinDecimals: 6,
                coinGeckoId: 'starname',
                coinImageUrl: window.location.origin + '/public/assets/tokens/iov.png',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/starname/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-emoney.keplr.app',
        rest: 'https://lcd-emoney.keplr.app',
        chainId: 'emoney-3',
        chainName: 'e-Money',
        stakeCurrency: {
            coinDenom: 'NGM',
            coinMinimalDenom: 'ungm',
            coinDecimals: 6,
            coinGeckoId: 'e-money',
            coinImageUrl: window.location.origin + '/public/assets/tokens/ngm.png',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('emoney'),
        currencies: [
            {
                coinDenom: 'NGM',
                coinMinimalDenom: 'ungm',
                coinDecimals: 6,
                coinGeckoId: 'e-money',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ngm.png',
            },
            {
                coinDenom: 'EEUR',
                coinMinimalDenom: 'eeur',
                coinDecimals: 6,
                coinGeckoId: 'e-money-eur',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ngm.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'NGM',
                coinMinimalDenom: 'ungm',
                coinDecimals: 6,
                coinGeckoId: 'e-money',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ngm.png',
            },
        ],
        gasPriceStep: {
            low: 1,
            average: 1,
            high: 1,
        },
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://emoney.bigdipper.live/transactions/{txHash}',
    },
    {
        rpc: 'https://rpc-juno.itastakers.com',
        rest: 'https://lcd-juno.itastakers.com',
        chainId: 'juno-1',
        chainName: 'Juno',
        stakeCurrency: {
            coinDenom: 'JUNO',
            coinMinimalDenom: 'ujuno',
            coinDecimals: 6,
            coinGeckoId: 'juno-network',
            coinImageUrl: window.location.origin + '/public/assets/tokens/juno.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('juno'),
        currencies: [
            {
                coinDenom: 'JUNO',
                coinMinimalDenom: 'ujuno',
                coinDecimals: 6,
                coinGeckoId: 'juno-network',
                coinImageUrl: window.location.origin + '/public/assets/tokens/juno.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'JUNO',
                coinMinimalDenom: 'ujuno',
                coinDecimals: 6,
                coinGeckoId: 'juno-network',
                coinImageUrl: window.location.origin + '/public/assets/tokens/juno.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/juno/txs/{txHash}',
    },
    {
        rpc: 'https://rpc-microtick.keplr.app',
        rest: 'https://lcd-microtick.keplr.app',
        chainId: 'microtick-1',
        chainName: 'Microtick',
        stakeCurrency: {
            coinDenom: 'TICK',
            coinMinimalDenom: 'utick',
            coinDecimals: 6,
            coinGeckoId: 'pool:utick',
            coinImageUrl: window.location.origin + '/public/assets/tokens/tick.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('micro'),
        currencies: [
            {
                coinDenom: 'TICK',
                coinMinimalDenom: 'utick',
                coinDecimals: 6,
                coinGeckoId: 'pool:utick',
                coinImageUrl: window.location.origin + '/public/assets/tokens/tick.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'TICK',
                coinMinimalDenom: 'utick',
                coinDecimals: 6,
                coinGeckoId: 'pool:utick',
                coinImageUrl: window.location.origin + '/public/assets/tokens/tick.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://explorer.microtick.zone/transactions/{txHash}',
    },
    {
        rpc: 'https://mainnet-node.like.co/rpc',
        rest: 'https://mainnet-node.like.co',
        chainId: 'likecoin-mainnet-2',
        chainName: 'LikeCoin',
        stakeCurrency: {
            coinDenom: 'LIKE',
            coinMinimalDenom: 'nanolike',
            coinDecimals: 9,
            coinGeckoId: 'likecoin',
            coinImageUrl: window.location.origin + '/public/assets/tokens/likecoin.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('cosmos'),
        currencies: [
            {
                coinDenom: 'LIKE',
                coinMinimalDenom: 'nanolike',
                coinDecimals: 9,
                coinGeckoId: 'likecoin',
                coinImageUrl: window.location.origin + '/public/assets/tokens/likecoin.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'LIKE',
                coinMinimalDenom: 'nanolike',
                coinDecimals: 9,
                coinGeckoId: 'likecoin',
                coinImageUrl: window.location.origin + '/public/assets/tokens/likecoin.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://likecoin.bigdipper.live/transactions/{txHash}',
    },
    {
        rpc: 'https://rpc-impacthub.keplr.app',
        rest: 'https://lcd-impacthub.keplr.app',
        chainId: 'impacthub-3',
        chainName: 'IXO',
        stakeCurrency: {
            coinDenom: 'IXO',
            coinMinimalDenom: 'uixo',
            coinDecimals: 6,
            coinGeckoId: 'pool:uixo',
            coinImageUrl: window.location.origin + '/public/assets/tokens/ixo.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('ixo'),
        currencies: [
            {
                coinDenom: 'IXO',
                coinMinimalDenom: 'uixo',
                coinDecimals: 6,
                coinGeckoId: 'pool:uixo',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ixo.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'IXO',
                coinMinimalDenom: 'uixo',
                coinDecimals: 6,
                coinGeckoId: 'pool:uixo',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ixo.png',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://blockscan.ixo.world/transactions/{txHash}',
    },
    {
        rpc: 'https://rpc.bitcanna.io',
        rest: 'https://lcd.bitcanna.io',
        chainId: 'bitcanna-1',
        chainName: 'BitCanna',
        stakeCurrency: {
            coinDenom: 'BCNA',
            coinMinimalDenom: 'ubcna',
            coinDecimals: 6,
            coinGeckoId: 'bitcanna',
            coinImageUrl: window.location.origin + '/public/assets/tokens/bcna.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('bcna'),
        currencies: [
            {
                coinDenom: 'BCNA',
                coinMinimalDenom: 'ubcna',
                coinDecimals: 6,
                coinGeckoId: 'bitcanna',
                coinImageUrl: window.location.origin + '/public/assets/tokens/bcna.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'BCNA',
                coinMinimalDenom: 'ubcna',
                coinDecimals: 6,
                coinGeckoId: 'bitcanna',
                coinImageUrl: window.location.origin + '/public/assets/tokens/bcna.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
        explorerUrlToTx: 'https://www.mintscan.io/bitcanna/txs/{txHash}',
    },
    {
        rpc: 'https://rpc.explorebitsong.com',
        rest: 'https://lcd.explorebitsong.com',
        chainId: 'bitsong-2b',
        chainName: 'BitSong',
        stakeCurrency: {
            coinDenom: 'BTSG',
            coinMinimalDenom: 'ubtsg',
            coinDecimals: 6,
            coinGeckoId: 'pool:ubtsg',
            coinImageUrl: window.location.origin + '/public/assets/tokens/btsg.svg',
        },
        bip44: {
            coinType: 639,
        },
        bech32Config: Bech32Address.defaultBech32Config('bitsong'),
        currencies: [
            {
                coinDenom: 'BTSG',
                coinMinimalDenom: 'ubtsg',
                coinDecimals: 6,
                coinGeckoId: 'pool:ubtsg',
                coinImageUrl: window.location.origin + '/public/assets/tokens/btsg.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'BTSG',
                coinMinimalDenom: 'ubtsg',
                coinDecimals: 6,
                coinGeckoId: 'pool:ubtsg',
                coinImageUrl: window.location.origin + '/public/assets/tokens/btsg.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://explorebitsong.com/transactions/{txHash}',
    },
    {
        rpc: 'https://rpc-mainnet.blockchain.ki',
        rest: 'https://api-mainnet.blockchain.ki',
        chainId: 'kichain-2',
        chainName: 'Ki',
        stakeCurrency: {
            coinDenom: 'XKI',
            coinMinimalDenom: 'uxki',
            coinDecimals: 6,
            coinGeckoId: 'pool:uxki',
            coinImageUrl: window.location.origin + '/public/assets/tokens/ki.svg',
        },
        bip44: {
            coinType: 118,
        },
        bech32Config: Bech32Address.defaultBech32Config('ki'),
        currencies: [
            {
                coinDenom: 'XKI',
                coinMinimalDenom: 'uxki',
                coinDecimals: 6,
                coinGeckoId: 'pool:uxki',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ki.svg',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'XKI',
                coinMinimalDenom: 'uxki',
                coinDecimals: 6,
                coinGeckoId: 'pool:uxki',
                coinImageUrl: window.location.origin + '/public/assets/tokens/ki.svg',
            },
        ],
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/ki-chain/txs/{txHash}',
    },
    {
        rpc: 'https://rpc.gopanacea.org',
        rest: 'https://api.gopanacea.org',
        chainId: 'panacea-3',
        chainName: 'Panacea',
        stakeCurrency: {
            coinDenom: 'MED',
            coinMinimalDenom: 'umed',
            coinDecimals: 6,
            coinGeckoId: 'medibloc',
            coinImageUrl: window.location.origin + '/public/assets/tokens/med.png',
        },
        bip44: {
            coinType: 371,
        },
        bech32Config: Bech32Address.defaultBech32Config('panacea'),
        currencies: [
            {
                coinDenom: 'MED',
                coinMinimalDenom: 'umed',
                coinDecimals: 6,
                coinGeckoId: 'medibloc',
                coinImageUrl: window.location.origin + '/public/assets/tokens/med.png',
            },
        ],
        feeCurrencies: [
            {
                coinDenom: 'MED',
                coinMinimalDenom: 'umed',
                coinDecimals: 6,
                coinGeckoId: 'medibloc',
                coinImageUrl: window.location.origin + '/public/assets/tokens/med.png',
            },
        ],
        gasPriceStep: {
            low: 5,
            average: 7,
            high: 9,
        },
        features: ['stargate', 'ibc-transfer'],
        explorerUrlToTx: 'https://www.mintscan.io/medibloc/txs/{txHash}',
    },
];
